# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsC <- function(mu1, mu2, sigma1, sigma2, rho, N, burn) {
    .Call('_StatComp22017_gibbsC', PACKAGE = 'StatComp22017', mu1, mu2, sigma1, sigma2, rho, N, burn)
}

#' @title Compute TIL Score using Rcpp
#' @param LYM the number of patches of LYM
#' @param STR the number of patches of STR
#' @param TUM the number of patches of TUM
#' @param TIL3 the TIL Score of LYM
#' @param TIL7 the TIL Score of STR
#' @param TIL8 the TIL Score of TUM
#' @useDynLib StatComp22017
#' @export
til <- function(LYM, STR, TUM, TIL3, TIL7, TIL8) {
    .Call('_StatComp22017_til', PACKAGE = 'StatComp22017', LYM, STR, TUM, TIL3, TIL7, TIL8)
}

